import { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react';

const STORAGE_KEY = 'az.language';
const LanguageContext = createContext(null);

export const translations = {
  'Shop all': 'تسوقي الكل', 'Scents': 'العطور', 'Gift sets': 'مجموعات الهدايا', 'Our story': 'قصتنا',
  'Home': 'الرئيسية', 'Shop': 'المتجر', 'Search': 'بحث', 'Bag': 'الحقيبة', 'Menu': 'القائمة', 'Close': 'إغلاق',
  'Wishlist': 'قائمة الأمنيات', 'Contact': 'تواصل معنا', 'Contact us': 'تواصل معنا', 'My account': 'حسابي',
  'Sign in / Create account': 'تسجيل الدخول / إنشاء حساب', 'Search the collection': 'ابحثي في المجموعة',
  'Free gift cards with every trio box': 'بطاقات إهداء مجانية مع كل مجموعة ثلاثية',
  'Fine fragrance mists and gift boxes, made in Egypt for every mood you wear.': 'معطرات فاخرة ومجموعات هدايا صُنعت في مصر لتناسب كل مزاج.',
  'Subscribe': 'اشتراك', 'Join our beauty community': 'انضمي إلى مجتمع الجمال', 'Email address': 'البريد الإلكتروني',
  'Three moods. One you.': 'ثلاثة أجواء.. وأنتِ كما أنتِ.', 'Home': 'الرئيسية', 'Shop all': 'تسوقي الكل',
  'All': 'الكل', 'Mists': 'معطرات', 'Serums': 'سيروم', 'Calm and deep': 'هادئ وعميق', 'Bold': 'جريء', 'Soft': 'ناعم',
  'Best Selling': 'الأكثر مبيعًا', 'Featured': 'مميز', 'Newest': 'الأحدث', 'Price: Low to High': 'السعر: من الأقل للأعلى',
  'Price: High to Low': 'السعر: من الأعلى للأقل', 'Best Rated': 'الأعلى تقييمًا', 'Best Selling': 'الأكثر مبيعًا',
  'Refine': 'تصفية', 'Sort': 'ترتيب', 'Price': 'السعر', 'Scent profile': 'طابع العطر', 'Rating': 'التقييم', 'More': 'المزيد',
  'Any price': 'أي سعر', 'Under EGP 300': 'أقل من 300 جنيه', 'EGP 300 – 500': '300–500 جنيه', 'EGP 500 – 1,000': '500–1,000 جنيه', 'Over EGP 1,000': 'أكثر من 1,000 جنيه',
  'Any rating': 'أي تقييم', 'In stock only': 'المتوفر فقط', 'On sale': 'عليه خصم', 'AZ Original Products': 'منتجات AZ الأصلية',
  'clear': 'مسح', 'No scents found.': 'لم نعثر على منتجات.', 'Try another mood, or clear the filters and start again.': 'جرّبي اختيارًا آخر أو امسحي عوامل التصفية.', 'Clear filters': 'مسح عوامل التصفية',
  'Your bag': 'حقيبتك', 'Continue shopping': 'متابعة التسوق', 'Your bag is empty.': 'حقيبتك فارغة.', 'Three moods are waiting for you.': 'ثلاثة أجواء بانتظارك.',
  'Add': 'أضيفي', 'more for free delivery': 'للحصول على شحن مجاني', 'You’ve unlocked': 'أصبح الشحن', 'free delivery': 'مجانيًا',
  'Remove': 'إزالة', 'Promo code': 'رمز الخصم', 'Apply': 'تطبيق', 'applied': 'تم تطبيقه', 'Subtotal': 'المجموع الفرعي', 'Go to checkout': 'إتمام الشراء',
  'Shop the collection': 'تسوقي المجموعة', 'View all': 'عرض الكل', 'View details': 'عرض التفاصيل', 'The collection': 'المجموعة',
  'Questions, answered.': 'إجابات على أسئلتك.', 'Everything shoppers ask us, in one place.': 'كل ما يهمك من إجابات في مكان واحد.',
  'Scent is self-expression.': 'العطر تعبير عن شخصيتك.', 'Three moods, one wardrobe': 'ثلاثة أجواء في مجموعتك', 'Made to be given': 'هدية تستحق أن تُهدى',
  'Find my scent': 'اكتشفي عطرك', 'Shop the trio': 'تسوقي المجموعة الثلاثية', 'Gift-ready,': 'هدية جاهزة،', 'every time.': 'في كل مرة.',
  'Your wishlist': 'قائمة أمنياتك', 'No saved scents.': 'لا توجد عطور محفوظة.', 'Shop all': 'تسوقي الكل',
  'Welcome back.': 'أهلًا بعودتك.', 'YOUR AZ STORE ACCOUNT': 'حسابك في AZ Store', 'AZ STORE · YOUR PERSONAL SPACE': 'AZ STORE · مساحتك الخاصة',
  'Your name': 'اسمك', 'Full name': 'الاسم بالكامل', 'Email address': 'البريد الإلكتروني', 'Password': 'كلمة المرور', 'Confirm password': 'تأكيد كلمة المرور',
  'Hide': 'إخفاء', 'Show': 'إظهار', 'Forgot password?': 'نسيتِ كلمة المرور؟', 'Back to sign in': 'العودة لتسجيل الدخول', 'Continue shopping': 'متابعة التسوق',
  'Sign out': 'تسجيل الخروج', 'Your wishlist': 'قائمة أمنياتك', 'or continue with email': 'أو تابعي باستخدام البريد الإلكتروني',
  'Email': 'البريد الإلكتروني', 'Send message': 'إرسال الرسالة', 'We’re listening.': 'نحن هنا لمساعدتك.',
  'Order questions, scent advice, gift help — the AZ care team answers every message, usually within a day.': 'للاستفسار عن الطلبات أو اختيار العطر أو الهدايا، فريق AZ جاهز للرد عليكِ عادةً خلال يوم واحد.',
  'Checkout': 'إتمام الشراء', 'Back to bag': 'العودة إلى الحقيبة', 'Delivery': 'التوصيل', 'Delivery method': 'طريقة التوصيل', 'Payment': 'الدفع',
  'Order summary': 'ملخص الطلب', 'Total': 'الإجمالي', 'Free': 'مجاني', 'Transfer reference': 'رقم مرجع التحويل',
  'Reference from your transfer': 'الرقم المرجعي للتحويل', 'The store will confirm your transfer manually before preparing the order.': 'سيراجع المتجر التحويل يدويًا قبل تجهيز الطلب.',
  'Your orders': 'طلباتك', 'Refresh': 'تحديث', 'Order number': 'رقم الطلب', 'Customer': 'العميل', 'Products': 'المنتجات', 'Payment method': 'طريقة الدفع',
  'Address': 'العنوان', 'Order status': 'حالة الطلب', 'Thank you for your order.': 'شكرًا لطلبك.', 'Continue shopping': 'متابعة التسوق',
  'Admin Portal': 'لوحة الإدارة', 'Dashboard': 'لوحة المعلومات', 'Products': 'المنتجات', 'Orders': 'الطلبات', 'Categories': 'الفئات', 'Inventory': 'المخزون', 'Customers': 'العملاء', 'Settings': 'الإعدادات',
  'Logout': 'تسجيل الخروج', 'View store': 'عرض المتجر', 'Loading…': 'جارٍ التحميل…', 'Save': 'حفظ', 'Cancel': 'إلغاء', 'Delete': 'حذف', 'Edit': 'تعديل', 'Preview': 'معاينة', 'Upload': 'رفع',
  'Product': 'المنتج', 'Category': 'الفئة', 'Status': 'الحالة', 'Actions': 'الإجراءات', 'Image': 'الصورة', 'Price': 'السعر', 'Discount': 'الخصم', 'Stock': 'المخزون',
  'Create category': 'إنشاء فئة', 'Category name': 'اسم الفئة', 'Category image': 'صورة الفئة', 'Add Category': 'إضافة فئة', 'No products yet.': 'لا توجد منتجات بعد.',
  'Storefront': 'واجهة المتجر', 'Announcement bar': 'شريط الإعلان', 'Shown at the top of every customer page.': 'يظهر أعلى صفحات المتجر للعملاء.',
  'Free delivery threshold (EGP)': 'حد الشحن المجاني (جنيه)', 'Default low stock threshold': 'حد انخفاض المخزون الافتراضي',
  'Payment methods': 'طرق الدفع', 'Cash on delivery': 'الدفع عند الاستلام', 'Enable InstaPay': 'تفعيل إنستا باي', 'InstaPay account / payment address': 'حساب إنستا باي / عنوان الدفع',
  'Account holder name': 'اسم صاحب الحساب', 'Enable Vodafone Cash': 'تفعيل فودافون كاش', 'Vodafone Cash wallet number': 'رقم محفظة فودافون كاش',
  'Authentication': 'المصادقة', 'Save settings': 'حفظ الإعدادات', 'Settings saved.': 'تم حفظ الإعدادات.',
  'Three moods.': 'ثلاثة أجواء.', 'One you.': 'وأنتِ كما أنتِ.',
  'Fine fragrance mists, 220 ml. Pick a scent for tonight or give all three in one box.': 'معطرات فاخرة بحجم 220 مل. اختاري عطركِ لليلة أو أهدِي العطور الثلاثة في صندوق واحد.',
  'Four ways to wear AZ — three mists and the box that holds them all.': 'أربع طرق للاستمتاع بـ AZ — ثلاثة معطرات وصندوق يجمعها كلها.',
  'Three fragrances, three personalities. Choose the one that matches tonight.': 'ثلاثة عطور بثلاث شخصيات. اختاري ما يناسب أجواءكِ الليلة.',
  'The trio arrives in a black velvet-touch box with a thank-you card and a dedication card — wrapped, sealed and ready to give.': 'تصل المجموعة في صندوق أسود بملمس مخملي، مع بطاقة شكر وبطاقة إهداء، مغلفة وجاهزة لتقديمها.',
  'All three 220 ml mists in one box': 'المعطرات الثلاثة، كل منها 220 مل، في صندوق واحد', 'Two gift cards included with every trio': 'بطاقتا إهداء مع كل مجموعة ثلاثية',
  'Save 11% versus buying separately': 'وفّري 11٪ مقارنة بشرائها منفردة', 'Scent is the most honest thing you wear.': 'العطر أصدق ما ترتدينه.', 'AZ Store — Cairo': 'AZ Store — القاهرة',
  'Long-lasting, morning to night': 'ثبات يدوم من الصباح حتى المساء', 'Skin-safe formula': 'تركيبة آمنة على البشرة', 'Gift-ready packaging': 'تغليف جاهز للإهداء', 'Delivery across Egypt': 'توصيل إلى جميع أنحاء مصر',
  'AZ began in Cairo with a simple frustration: beautiful fragrance was either imported and expensive, or local and forgettable. We wanted a third way — small-batch fine fragrance mists, made here, priced honestly, and dressed like the luxury object they are.': 'بدأت AZ في القاهرة من ملاحظة بسيطة: العطور الجميلة إما مستوردة وباهظة، أو محلية وسريعة النسيان. أردنا خيارًا ثالثًا — معطرات فاخرة تُصنع هنا بدفعات صغيرة، بسعر عادل ومظهر يليق بفخامتها.',
  'We don’t release twenty scents a season. We release three, and we obsess over them: Through The Night for the calm and the deep, Black Kiss for the bold, Million Dreams for the soft and dreamy. One of them is always you — and some nights, all three are.': 'لا نطلق عشرين عطرًا في الموسم. نختار ثلاثة ونعتني بكل تفاصيلها: Through The Night للأجواء الهادئة والعميقة، وBlack Kiss للجريئة، وMillion Dreams للناعمة الحالمة. ستجدين ما يشبهكِ بينها، وربما تختارينها كلها في بعض الليالي.',
  'Every mist is 220 ml of skin-safe, alcohol-balanced formula, filled in dated batches and rested before it ships, so the scent you spray in the morning is still with you at night.': 'كل معطر بحجم 220 مل، بتركيبة متوازنة وآمنة على البشرة. يُعبأ ضمن دفعات مؤرخة ويُترك ليستقر قبل الشحن، ليبقى أثره معكِ من الصباح حتى المساء.',
  'A fragrance is the most personal gift you can give — and the hardest to get right. The AZ trio box solves that: all three moods in one black velvet-touch box, with a thank-you card and a dedication card tucked under the lid.': 'العطر هدية شخصية جدًا، واختيارها ليس سهلًا دائمًا. تجمع لكِ علبة AZ الثلاثية الأجواء الثلاثة في صندوق أسود بملمس مخملي، مع بطاقة شكر وبطاقة إهداء تحت الغطاء.',
  'From our studio in Cairo to doorsteps across Egypt, every box is packed by hand, sealed, and sent with the same care we would give a gift of our own.': 'من استوديو AZ في القاهرة إلى أبواب المنازل في أنحاء مصر، نجهز كل صندوق يدويًا ونرسله بعناية كأنه هدية منا.',
  'The three AZ mists standing on black marble with golden smoke': 'معطرات AZ الثلاثة على رخام أسود ودخان ذهبي', 'AZ black gift box with gold monogram on bronze satin': 'صندوق هدايا AZ الأسود بشعار ذهبي على قماش برونزي',
  'Open AZ gift box with three mists and thank-you cards on bronze satin': 'صندوق هدايا AZ مفتوح ويضم ثلاثة معطرات وبطاقات شكر على قماش برونزي',
  'Questions, answered.': 'إجابات على أسئلتك.', 'Everything shoppers ask us, in one place.': 'كل ما يهمكِ من إجابات في مكان واحد.',
  'How long does delivery take?': 'كم يستغرق التوصيل؟', 'Standard delivery takes 2 to 4 working days anywhere in Egypt. Express delivery arrives the next working day for Cairo and Giza, and within 2 days for most other governorates.': 'يستغرق التوصيل العادي من يومين إلى 4 أيام عمل في أنحاء مصر. يصل التوصيل السريع في يوم العمل التالي للقاهرة والجيزة، وخلال يومين لمعظم المحافظات الأخرى.',
  'What payment methods do you accept?': 'ما طرق الدفع المتاحة؟', 'Available methods appear during checkout. The store can accept cash on delivery or enable manual InstaPay and Vodafone Cash transfers. For transfers, pay the displayed destination and enter your transfer reference; the store verifies it manually. Card payments are not available yet.': 'تظهر طرق الدفع المتاحة عند إتمام الطلب. يمكن الدفع نقدًا عند الاستلام أو عبر تحويل يدوي باستخدام إنستا باي أو فودافون كاش. أدخلي الرقم المرجعي للتحويل ليتمكن المتجر من مراجعته يدويًا. الدفع بالبطاقات غير متاح حاليًا.',
  'Can I return a product?': 'هل يمكنني إرجاع المنتج؟', 'Unopened products can be returned within 14 days of delivery for a full refund. If your order arrived damaged or incorrect, contact us within 48 hours and we will replace it right away.': 'يمكن إرجاع المنتجات غير المفتوحة خلال 14 يومًا من الاستلام لاسترداد كامل المبلغ. إذا وصل طلبك تالفًا أو غير صحيح، تواصلي معنا خلال 48 ساعة وسنستبدله فورًا.',
  'Are your products authentic?': 'هل منتجاتكم أصلية؟', 'Yes. Every AZ mist is formulated and filled under our own supervision in small, dated batches. Each bottle carries a batch code you can verify with our customer care team.': 'نعم. تُحضّر معطرات AZ وتُعبأ تحت إشرافنا ضمن دفعات صغيرة ومؤرخة. تحمل كل عبوة رقم دفعة يمكن التحقق منه عبر فريق خدمة العملاء.',
  'Do you deliver across Egypt?': 'هل توصلون إلى جميع أنحاء مصر؟', 'We deliver to all 27 governorates. Standard delivery is EGP 60 and express is EGP 110. Orders over EGP 1,800 ship free with standard delivery.': 'نوصل إلى جميع محافظات مصر. رسوم التوصيل العادي 60 جنيهًا والسريع 110 جنيهات. الطلبات التي تتجاوز 1,800 جنيه تحصل على توصيل عادي مجاني.',
  'We’re listening.': 'نحن هنا لمساعدتكِ.', 'Order questions, scent advice, gift help — the AZ care team answers every message, usually within a day.': 'للاستفسار عن الطلبات أو اختيار العطر أو الهدايا، فريق AZ جاهز للرد عليكِ عادةً خلال يوم واحد.',
  'Please tell us your name.': 'اكتبي اسمكِ من فضلك.', 'Enter a valid email address.': 'أدخلي بريدًا إلكترونيًا صحيحًا.', 'Tell us a little more (at least 10 characters).': 'أخبرينا بالمزيد (10 أحرف على الأقل).', 'Message sent — we’ll reply within 24 hours': 'تم إرسال رسالتك — سنرد خلال 24 ساعة.',
  'Name': 'الاسم', 'Phone': 'الهاتف', 'Message': 'الرسالة', 'Hours': 'ساعات العمل', 'Sat to Thu, 10:00 – 20:00': 'السبت إلى الخميس، 10:00 – 20:00',
  'No order found.': 'لم يتم العثور على الطلب.', 'We couldn’t find an order for this session. Head back to the store whenever you’re ready.': 'لم نعثر على طلب في هذه الجلسة. يمكنك العودة إلى المتجر في أي وقت.',
  'Need help?': 'هل تحتاجين للمساعدة؟', 'Thank you for your order.': 'شكرًا لطلبك.', 'We’ve received your order and we’re already picking your bottles. A confirmation SMS is on its way to': 'استلمنا طلبك وبدأنا تجهيز المنتجات. ستصلك رسالة تأكيد على الرقم',
  'We received your reference': 'استلمنا الرقم المرجعي', 'Your order will be confirmed after payment verification.': 'سيتم تأكيد طلبك بعد مراجعة الدفع.', 'Payment method': 'طريقة الدفع',
  'Scent notes': 'مكونات العطر', 'How to use': 'طريقة الاستخدام', 'Ingredients': 'المكونات', 'Benefits': 'المميزات', 'Delivery and returns': 'التوصيل والإرجاع',
  'Standard delivery 2 to 4 days (EGP 60), express next day (EGP 110). Free standard delivery over EGP 1,800. Unopened products can be returned within 14 days.': 'التوصيل العادي خلال يومين إلى 4 أيام (60 جنيهًا)، والسريع في اليوم التالي (110 جنيهات). التوصيل العادي مجاني للطلبات فوق 1,800 جنيه. يمكن إرجاع المنتجات غير المفتوحة خلال 14 يومًا.',
  'Spray generously on clean skin from 15 cm — wrists, neck and over clothing.': 'رشي بسخاء على بشرة نظيفة من مسافة 15 سم — على المعصمين والرقبة وفوق الملابس.',
  'Bold and enchanting, with a trace that’s hard to forget.': 'جريء وساحر، بأثر يصعب نسيانه.', 'Bold and enchanting, with a trace you won’t forget.': 'جريء وساحر، بأثر لن تنسيه.', 'Mysterious and refreshing, with a pull that’s hard to resist.': 'غامض ومنعش، بجاذبية يصعب مقاومتها.', 'Soft and dreamy, made for your delicate side.': 'ناعم وحالم، لجانبكِ الرقيق.', 'All three moods in one gift-ready box.': 'الأجواء الثلاثة في صندوق واحد جاهز للإهداء.',
  'Depth, freshness and a pull you can’t refuse — for nights that refuse to end.': 'عمق وانتعاش وجاذبية لا تُقاوم — لليالٍ لا تنتهي.', 'Daring, witching, unforgettable — a trace that lingers long after you leave.': 'جريء وساحر ولا يُنسى — أثر يبقى طويلًا بعد رحيلكِ.', 'Soft, dreamy, sweet — for your most delicate moments.': 'ناعم وحالم وعذب — لأرق لحظاتكِ.', 'Three scents, one black box, two gift cards — the present that never misses.': 'ثلاثة عطور في صندوق أسود واحد وبطاقتا إهداء — هدية لا تخطئ الاختيار.',
  'Night flowers': 'زهور ليلية', 'Fresh fruit': 'فاكهة منعشة', 'Warm woods': 'أخشاب دافئة', 'Luxurious flowers': 'زهور فاخرة', 'Warm vanilla': 'فانيليا دافئة', 'Seductive musk': 'مسك جذاب', 'Rose blooms': 'بتلات الورد', 'Sweet fruit': 'فاكهة حلوة', 'Soft musk': 'مسك ناعم',
  'In stock': 'متوفر', 'Out of Stock': 'نفد المخزون', 'Low Stock': 'مخزون منخفض', 'Sold out': 'نفد', 'Add to bag': 'أضيفي إلى الحقيبة', 'Add to Bag': 'أضيفي إلى الحقيبة', 'Save to wishlist': 'أضيفي إلى الأمنيات', 'Remove from wishlist': 'إزالة من الأمنيات', 'Buy the trio box and save': 'اشتري المجموعة الثلاثية ووفّري', 'Complete the wardrobe': 'أكملي مجموعتك',
  'Go to checkout': 'الانتقال للدفع', 'Qty': 'الكمية', 'reviews': 'تقييمًا', 'product': 'منتج', 'products': 'منتجات', 'order': 'طلب', 'orders': 'طلبات', 'items': 'منتجات', 'customers': 'عميل',
  'Search products': 'ابحثي عن المنتجات', 'Search by name, scent or mood': 'ابحثي بالاسم أو العطر أو المزاج', 'What are you in the mood for?': 'ما العطر الذي يناسب مزاجكِ؟',
  'No scents found. Try “night”, “bold” or “gift”.': 'لم نعثر على عطور. جرّبي «نايت» أو «جريء» أو «هدية».', 'Popular tonight: Black Kiss · gift box · rose · night flowers': 'اختيارات الليلة: Black Kiss · صندوق هدايا · ورد · زهور ليلية',
  'Search results for': 'نتائج البحث عن', 'Choose size': 'اختاري الحجم', 'Show image': 'عرض الصورة', 'Only': 'لم يتبقَ سوى', 'left in stock': 'في المخزون',
  'Phone number': 'رقم الهاتف', 'Governorate': 'المحافظة', 'City': 'المدينة', 'Full address': 'العنوان بالكامل', 'Apartment / Building': 'الشقة / المبنى', 'Apartment or building': 'الشقة أو المبنى', 'Additional notes': 'ملاحظات إضافية',
  'In stock only': 'المتوفر فقط', 'On sale': 'عليه خصم', 'All categories': 'كل الفئات', 'All orders': 'كل الطلبات', 'Pending fulfilment': 'بانتظار التجهيز', 'Pending': 'قيد الانتظار', 'Paid': 'مدفوع', 'Verification Required': 'مطلوب التحقق', 'Failed': 'فشل', 'Refunded': 'مسترد',
  'Order Received': 'تم استلام الطلب', 'Payment Confirmed': 'تم تأكيد الدفع', 'Preparing Order': 'جارٍ تجهيز الطلب', 'Out for Delivery': 'خرج للتوصيل', 'Delivered': 'تم التوصيل', 'Received': 'تم الاستلام', 'Payment': 'الدفع', 'Preparing': 'قيد التجهيز', 'Out for delivery': 'خرج للتوصيل', 'Cancelled': 'ملغي',
  'Order ID': 'رقم الطلب', 'Date': 'التاريخ', 'Items': 'المنتجات', 'Payment status': 'حالة الدفع', 'Status of order': 'حالة الطلب', 'Payment status of order': 'حالة الدفع للطلب', 'Verify payment': 'تأكيد الدفع',
  'Recent orders': 'أحدث الطلبات', 'View all': 'عرض الكل', 'live in store': 'متاح في المتجر', 'all time': 'الإجمالي', 'not yet delivered': 'لم يتم توصيله بعد', 'Revenue': 'الإيرادات', 'excludes cancelled': 'باستثناء الملغي', 'products at or below threshold': 'منتج عند الحد أو أقل من المخزون', 'No orders yet.': 'لا توجد طلبات بعد.',
  'Low stock alerts': 'تنبيهات انخفاض المخزون', 'Manage inventory': 'إدارة المخزون', 'Every size is comfortably in stock.': 'كل الأحجام متوفرة بكمية جيدة.', 'Catalog health': 'حالة الكتالوج', 'Total spent': 'إجمالي الإنفاق', 'Last order': 'آخر طلب', 'No customers yet.': 'لا يوجد عملاء بعد.',
  'Payment card numbers, CVVs and banking passwords are never collected or shown here.': 'لا يتم جمع أو عرض أرقام البطاقات أو رموز CVV أو كلمات مرور الحسابات البنكية هنا.', 'Stock by SKU': 'المخزون حسب رمز المنتج',
  'Status is calculated automatically: stock above the threshold is': 'تُحسب الحالة تلقائيًا: إذا تجاوز المخزون الحد المحدد فهو', 'at or below it is': 'وعند الحد أو أقل فهو', 'zero is': 'وإذا كان صفرًا فهو', 'Current stock': 'المخزون الحالي', 'Low stock threshold': 'حد انخفاض المخزون', 'Threshold': 'الحد',
  'Products': 'المنتجات', 'Orders': 'الطلبات', 'Categories': 'الفئات', 'Inventory': 'المخزون', 'Customers': 'العملاء', 'Settings': 'الإعدادات', 'Actions': 'الإجراءات', 'Category': 'الفئة', 'Discount': 'الخصم', 'Edit': 'تعديل', 'Preview': 'معاينة', 'Duplicate': 'نسخ', 'Restore': 'استعادة', 'Archive': 'أرشفة',
  'Active': 'نشط', 'Draft': 'مسودة', 'Archived': 'مؤرشف', 'In': 'متوفر', 'Out': 'نفد', 'Low': 'منخفض', 'Search by name, SKU, category, brand or ID…': 'ابحث بالاسم أو رمز المنتج أو الفئة أو العلامة أو المعرّف…',
  'All categories': 'كل الفئات', 'Any status': 'أي حالة', 'Any stock': 'أي مخزون', 'In stock': 'متوفر', 'Low stock': 'مخزون منخفض', 'Out of stock': 'نفد المخزون', 'Under EGP 300': 'أقل من 300 جنيه', 'EGP 300 – 600': '300–600 جنيه', 'Over EGP 600': 'أكثر من 600 جنيه', 'Discount: any': 'الخصم: الكل', 'On discount': 'عليه خصم', 'No discount': 'بدون خصم',
  'Create category': 'إنشاء فئة', 'Category name': 'اسم الفئة', 'Category image': 'صورة الفئة', 'Add Category': 'إضافة فئة', 'Renaming also moves every product assigned to this category.': 'سيؤدي تغيير الاسم إلى تحديث فئة كل المنتجات المرتبطة بها.',
  'Please enter your full name.': 'أدخلي اسمكِ بالكامل.', 'Enter a valid Egyptian mobile number (e.g. 01012345678).': 'أدخلي رقم هاتف مصريًا صحيحًا (مثال: 01012345678).', 'That email address doesn’t look right.': 'تحققي من صحة البريد الإلكتروني.', 'Choose your governorate.': 'اختاري المحافظة.', 'Please enter your city.': 'أدخلي اسم المدينة.', 'Please enter your full street address.': 'أدخلي عنوان الشارع بالكامل.', 'Enter the transfer reference shown in your payment app.': 'أدخلي الرقم المرجعي الظاهر في تطبيق الدفع.',
  'Cairo': 'القاهرة', 'Giza': 'الجيزة', 'Alexandria': 'الإسكندرية', 'Qalyubia': 'القليوبية', 'Dakahlia': 'الدقهلية', 'Sharqia': 'الشرقية', 'Gharbia': 'الغربية', 'Monufia': 'المنوفية', 'Beheira': 'البحيرة', 'Kafr El Sheikh': 'كفر الشيخ', 'Damietta': 'دمياط', 'Port Said': 'بورسعيد', 'Ismailia': 'الإسماعيلية', 'Suez': 'السويس', 'Matrouh': 'مطروح', 'Fayoum': 'الفيوم', 'Beni Suef': 'بني سويف', 'Minya': 'المنيا', 'Assiut': 'أسيوط', 'Sohag': 'سوهاج', 'Qena': 'قنا', 'Luxor': 'الأقصر', 'Aswan': 'أسوان', 'Red Sea': 'البحر الأحمر', 'New Valley': 'الوادي الجديد', 'North Sinai': 'شمال سيناء', 'South Sinai': 'جنوب سيناء',
  'Standard': 'عادي', 'Express': 'سريع', '2 to 4 days': 'من يومين إلى 4 أيام', 'Next day': 'اليوم التالي', 'Cash on delivery': 'الدفع عند الاستلام', 'Transfer manually to the store account.': 'تحويل يدوي إلى حساب المتجر.', 'Transfer manually to the store wallet.': 'تحويل يدوي إلى محفظة المتجر.', 'Transfer': 'حوّلي', 'to this InstaPay account:': 'إلى حساب إنستا باي هذا:', 'to this Vodafone Cash number:': 'إلى رقم فودافون كاش هذا:', 'Reference from your transfer': 'الرقم المرجعي للتحويل', 'The store will confirm your transfer manually before preparing the order.': 'سيراجع المتجر التحويل يدويًا قبل تجهيز الطلب.',
  'No products match these filters.': 'لا توجد منتجات تطابق عوامل التصفية.', 'Customer preview': 'معاينة العميل', 'Save': 'حفظ', 'Delete Product': 'حذف المنتج', 'Delete Product?': 'هل تريد حذف المنتج؟', 'Archive Product?': 'هل تريد أرشفة المنتج؟', 'No orders in this view.': 'لا توجد طلبات في هذا العرض.', 'No customers yet.': 'لا يوجد عملاء بعد.',
  'Search products': 'ابحث عن المنتجات', 'Open menu': 'فتح القائمة', 'Open admin menu': 'فتح قائمة الإدارة', 'AZ Store home': 'الصفحة الرئيسية لمتجر AZ',
  'Please enter a valid email address': 'أدخلي بريدًا إلكترونيًا صحيحًا.', 'Welcome to the AZ community': 'أهلًا بكِ في مجتمع AZ.', 'Email address for newsletter': 'البريد الإلكتروني للنشرة البريدية', 'Shop': 'المتجر', 'Customer Service': 'خدمة العملاء', 'Company': 'الشركة', 'Best sellers': 'الأكثر مبيعًا', 'New arrivals': 'وصل حديثًا', 'Shipping & Delivery': 'الشحن والتوصيل', 'Returns & Refunds': 'الإرجاع والاسترداد', 'FAQ': 'الأسئلة الشائعة', 'Privacy Policy': 'سياسة الخصوصية', 'Terms & Conditions': 'الشروط والأحكام', 'Contact': 'تواصل معنا',
  'Join our beauty community': 'انضمي إلى مجتمع الجمال', 'You have been signed out.': 'تم تسجيل خروجك.', 'YOUR AZ STORE ACCOUNT': 'حسابك في AZ Store', 'Signed in as': 'تم تسجيل الدخول باسم', 'AZ STORE · YOUR PERSONAL SPACE': 'AZ STORE · مساحتك الخاصة', 'Create your account.': 'أنشئي حسابك.', 'Reset your password.': 'إعادة تعيين كلمة المرور.', 'Save your favourites and enjoy a more personal AZ Store experience.': 'احفظي منتجاتك المفضلة واستمتعي بتجربة AZ Store تناسبك.', 'Sign in to continue your AZ Store experience.': 'سجّلي الدخول لمتابعة تجربتك في AZ Store.', 'Your name': 'اسمك', 'At least 8 characters': '8 أحرف على الأقل', 'Your password': 'كلمة المرور', 'Re-enter your password': 'أعيدي إدخال كلمة المرور', 'I agree to the': 'أوافق على', 'and': 'و', 'Already have an account?': 'لديكِ حساب بالفعل؟', 'New to AZ Store?': 'جديدة على AZ Store؟', 'Create account': 'إنشاء حساب', 'Send reset link': 'إرسال رابط إعادة التعيين', 'Please wait…': 'يرجى الانتظار…', 'Please enter your name.': 'أدخلي اسمكِ من فضلك.', 'Enter your email address.': 'أدخلي بريدك الإلكتروني.', 'Enter your password.': 'أدخلي كلمة المرور.', 'Choose a password with at least 8 characters.': 'اختاري كلمة مرور من 8 أحرف على الأقل.', 'Add at least one letter to your password.': 'أضيفي حرفًا واحدًا على الأقل لكلمة المرور.', 'Add at least one number to your password.': 'أضيفي رقمًا واحدًا على الأقل لكلمة المرور.', 'The passwords do not match.': 'كلمتا المرور غير متطابقتين.', 'Please accept the Terms & Conditions and Privacy Policy.': 'يرجى الموافقة على الشروط والأحكام وسياسة الخصوصية.',
  'Email address': 'البريد الإلكتروني', 'Please enter your full name.': 'أدخلي اسمكِ بالكامل.', 'Phone number': 'رقم الهاتف', 'Full address': 'العنوان بالكامل', 'Payment method': 'طريقة الدفع', 'Place order': 'تأكيد الطلب', 'Placing order…': 'جارٍ تأكيد الطلب…', 'The store has no payment method enabled. Contact the store owner.': 'لا توجد وسيلة دفع مفعّلة حاليًا. تواصلي مع صاحب المتجر.', 'Prices in Egyptian pounds.': 'الأسعار بالجنيه المصري.', 'Pay the courier when your order arrives.': 'ادفعي للمندوب عند وصول طلبك.', 'Your transfer will be manually verified by the store.': 'سيراجع المتجر تحويلك يدويًا.', 'Add a scent or two before checking out.': 'أضيفي عطرًا أو اثنين قبل إتمام الشراء.', 'Apartment / Building': 'الشقة / المبنى', 'Additional notes': 'ملاحظات إضافية', 'Promo': 'رمز الخصم',
  'Admin Portal': 'لوحة الإدارة', 'Sign in to manage products, orders and inventory.': 'سجّل الدخول لإدارة المنتجات والطلبات والمخزون.', 'or use email and password': 'أو سجّل بالبريد الإلكتروني وكلمة المرور', 'Create password': 'إنشاء كلمة مرور', 'Remember me on this device': 'تذكرني على هذا الجهاز', 'Login': 'تسجيل الدخول', 'Back to login': 'العودة لتسجيل الدخول', 'First time? Create the admin account': 'أول مرة؟ أنشئ حساب الإدارة', 'Only the authorized admin email can create this account. Email verification is required.': 'يمكن للبريد الإلكتروني الإداري المصرح به فقط إنشاء هذا الحساب. يجب تأكيد البريد.', 'Enter your admin email and password.': 'أدخل بريد الإدارة وكلمة المرور.',
  'AZ Original Products': 'منتجات AZ الأصلية', 'Free': 'مجاني', 'Yes': 'نعم', 'No': 'لا',
  'AZ Store collects only the information needed to fulfil your order: your name, phone number, delivery address and, if you provide it, your email address. We use it to deliver your order, send order updates and, if you subscribe, our newsletter.': 'يجمع AZ Store المعلومات اللازمة لتنفيذ طلبك فقط: الاسم ورقم الهاتف وعنوان التوصيل والبريد الإلكتروني عند تقديمه. نستخدمها لتوصيل الطلب وإرسال تحديثاته، وإرسال النشرة البريدية عند الاشتراك بها.',
  'Depending on the options enabled by the store, you may pay cash on delivery or transfer manually through InstaPay or Vodafone Cash. For manual transfers, we record the reference you submit so the store can verify the payment. AZ Store does not collect card numbers, CVV codes, banking passwords, or online payment credentials.': 'بحسب وسائل الدفع المفعلة، يمكنك الدفع نقدًا عند الاستلام أو التحويل يدويًا عبر إنستا باي أو فودافون كاش. نسجل الرقم المرجعي الذي ترسلينه كي يتمكن المتجر من التحقق من الدفع. لا يجمع AZ Store أرقام البطاقات أو رموز CVV أو كلمات مرور الحسابات البنكية أو بيانات الدفع الإلكترونية.',
  'Order information is stored in the AZ Store Firebase database so the store administrator can fulfil orders and customers can check delivery status. Delivery details may be shared with the delivery provider to complete your order.': 'تُخزن معلومات الطلب في قاعدة بيانات AZ Store على Firebase ليتمكن مسؤول المتجر من تجهيز الطلبات وليتابع العملاء حالة التوصيل. قد تتم مشاركة تفاصيل التوصيل مع شركة التوصيل لتنفيذ طلبك.',
  'To delete your data or ask what we hold about you, email azstore700@gmail.com and we will respond within 30 days.': 'لحذف بياناتك أو الاستفسار عن البيانات المحفوظة لدينا، راسلينا على azstore700@gmail.com وسنرد خلال 30 يومًا.',
  'All prices are shown in Egyptian pounds. Orders are subject to confirmation by the store. Manual InstaPay and Vodafone Cash transfers must be verified by the store before the order is prepared.': 'تُعرض الأسعار بالجنيه المصري. تخضع الطلبات لتأكيد المتجر. يجب على المتجر مراجعة تحويلات إنستا باي وفودافون كاش يدويًا قبل تجهيز الطلب.',
  'Unopened products may be returned within 14 days of delivery for a full refund. Damaged or incorrect orders must be reported within 48 hours of delivery for a free replacement.': 'يمكن إرجاع المنتجات غير المفتوحة خلال 14 يومًا من الاستلام لاسترداد كامل المبلغ. يجب الإبلاغ عن الطلبات التالفة أو غير الصحيحة خلال 48 ساعة من الاستلام لاستبدالها مجانًا.',
  'Delivery estimates (2 to 4 days standard, next day express) begin once an order is confirmed. Forces outside our control — weather, national holidays, carrier strikes — may extend these windows.': 'تبدأ مدة التوصيل التقديرية (من يومين إلى 4 أيام للعادي، واليوم التالي للسريع) بعد تأكيد الطلب. قد تؤدي ظروف خارجة عن إرادتنا — مثل الطقس والعطلات الرسمية وإضرابات شركات التوصيل — إلى تأخير الموعد.',
  'By placing an order you agree to provide accurate delivery and contact information. AZ Store reserves the right to refuse or cancel orders where information cannot be verified.': 'بتقديم الطلب، توافقين على إدخال بيانات تواصل وتوصيل صحيحة. يحتفظ AZ Store بحقه في رفض أو إلغاء الطلبات التي يتعذر التحقق من بياناتها.',
  'AZ is an Egyptian fragrance house built on one idea: scent is self-expression. Three moods, one you.': 'AZ علامة عطور مصرية تقوم على فكرة واحدة: العطر تعبير عن الشخصية. ثلاثة أجواء، وأنتِ كما أنتِ.',
  'About AZ Store': 'عن AZ Store', 'Company': 'الشركة', 'Contact us': 'تواصل معنا', 'Profile link not set': 'رابط الحساب غير مضاف',
  'The store will confirm your transfer manually before preparing the order.': 'سيراجع المتجر التحويل يدويًا قبل تجهيز الطلب.', 'in stock': 'متوفر', 'out of stock': 'نفد المخزون',
  'Please enter your full name.': 'أدخلي اسمكِ بالكامل.', 'Enter a valid Egyptian mobile number (e.g. 01012345678).': 'أدخلي رقم هاتف مصريًا صحيحًا (مثال: 01012345678).',
  'Only the authorized admin email can create this account. Email verification is required.': 'يمكن للبريد الإلكتروني الإداري المصرح به فقط إنشاء هذا الحساب. يجب تأكيد البريد.', 'Administrator access is managed by Firebase Authentication and restricted to the verified': 'تُدار صلاحيات الإدارة عبر Firebase Authentication وتقتصر على البريد الموثق', 'account. Use “Forgot password?” on the admin login page to change a forgotten password.': 'استخدم «نسيت كلمة المرور؟» في صفحة دخول الإدارة لإعادة تعيين كلمة المرور.',
  'product type': 'نوع المنتج', 'Product type': 'نوع المنتج', 'Gift set': 'مجموعة هدايا', 'Mist': 'معطر', 'Serum': 'سيروم',
  'All three in one box': 'الثلاثة في صندوق واحد', 'Best seller': 'الأكثر مبيعًا', 'Save 11%': 'وفّري 11٪',
  'Standard': 'عادي', 'Express': 'سريع', '2 to 4 days': 'من يومين إلى 4 أيام', 'Next day': 'اليوم التالي',
  'Add Product': 'إضافة منتج', 'Edit product': 'تعديل المنتج', 'Basic information': 'المعلومات الأساسية', 'Product name': 'اسم المنتج', 'Primary SKU': 'رمز المنتج الأساسي', 'Brand': 'العلامة التجارية', 'Short description': 'وصف مختصر', 'Full description': 'الوصف الكامل', 'Pricing': 'التسعير', 'Price (EGP)': 'السعر (جنيه)', 'Compare-at price': 'السعر قبل الخصم', 'Discount %': 'نسبة الخصم ٪', 'Stock quantity (primary size)': 'كمية المخزون (الحجم الأساسي)', 'Available for sale (primary size in stock)': 'متاح للبيع (الحجم الأساسي متوفر)', 'Sizes & stock (variations)': 'الأحجام والمخزون (الخيارات)', 'The first size is the primary one shown on cards and used by the pricing fields above.': 'الحجم الأول هو الحجم الأساسي الظاهر على بطاقات المنتجات وتُستخدم بياناته في التسعير أعلاه.', 'Size label': 'اسم الحجم', 'Add size': 'إضافة حجم', 'Product details': 'تفاصيل المنتج', 'Volume': 'الحجم', 'Weight': 'الوزن', 'Scent notes (comma separated)': 'مكونات العطر (افصل بينها بفواصل)', 'Scent family': 'عائلة العطر', 'Ingredients (one per line)': 'المكونات (كل مكون في سطر)', 'Benefits (one per line)': 'المميزات (كل ميزة في سطر)', 'Product type': 'نوع المنتج', 'Badge (e.g. Best seller)': 'شارة (مثل: الأكثر مبيعًا)', 'Accent colour': 'اللون المميز', 'Images': 'الصور', 'Product status': 'حالة المنتج', 'Only active products appear in the customer store. Drafts and archived products stay here in the admin.': 'تظهر المنتجات النشطة فقط للعملاء. تبقى المسودات والمنتجات المؤرشفة في لوحة الإدارة.', 'Saving…': 'جارٍ الحفظ…', 'Save changes': 'حفظ التغييرات', 'Create product': 'إنشاء المنتج',
  'New Arrivals': 'وصل حديثًا', 'Replace': 'استبدال', 'Clear': 'مسح', 'categories': 'فئة', 'Delete Category?': 'هل تريد حذف الفئة؟', 'Delete Category': 'حذف الفئة', 'Edit category': 'تعديل الفئة', 'Category name is required.': 'اسم الفئة مطلوب.', 'Category created.': 'تم إنشاء الفئة.', 'Category updated.': 'تم تحديث الفئة.', 'Category deleted.': 'تم حذف الفئة.', 'Are you sure you want to delete': 'هل أنت متأكد من حذف', 'Categories with products assigned cannot be deleted.': 'لا يمكن حذف فئة مرتبطة بمنتجات.',
  'Image upload failed. Please try again.': 'فشل رفع الصورة. يرجى المحاولة مجددًا.', 'A product needs at least one image.': 'يحتاج المنتج إلى صورة واحدة على الأقل.', 'Primary': 'أساسية', 'Make primary': 'اجعلها الصورة الأساسية', 'Move earlier': 'تحريك للأعلى', 'Move later': 'تحريك للأسفل', 'Delete image': 'حذف الصورة', 'The first image is the main image customers see. Images are resized to fit the store database limit.': 'الصورة الأولى هي الصورة الأساسية التي يراها العملاء. يتم تصغير الصور لتناسب حد قاعدة بيانات المتجر.', 'Add': 'إضافة',
  'Please enter a valid email address': 'أدخلي بريدًا إلكترونيًا صحيحًا.', 'Welcome to the AZ community': 'أهلًا بكِ في مجتمع AZ.', 'Email address for newsletter': 'البريد الإلكتروني للنشرة البريدية', 'AZ Store — Bodysplash & Serum': 'AZ Store — بودي سبلاش وسيروم',
  'Added to your bag': 'تمت الإضافة إلى حقيبتك.', 'Removed from wishlist': 'تمت الإزالة من قائمة الأمنيات.', 'Saved to wishlist': 'تمت الإضافة إلى قائمة الأمنيات.', 'Unable to load the store.': 'تعذر تحميل المتجر.', 'Unable to save product.': 'تعذر حفظ المنتج.', 'Unable to save inventory.': 'تعذر حفظ المخزون.', 'Inventory updated.': 'تم تحديث المخزون.', 'Stock and threshold must be whole numbers of 0 or more.': 'يجب أن تكون الكمية والحد أعدادًا صحيحة تساوي صفرًا أو أكثر.', 'Unable to save settings.': 'تعذر حفظ الإعدادات.', 'Thresholds must be valid numbers of 0 or more.': 'يجب أن تكون الحدود أرقامًا صحيحة تساوي صفرًا أو أكثر.', 'Add the InstaPay account before enabling it.': 'أضيفي حساب إنستا باي قبل تفعيله.', 'Add the Vodafone Cash number before enabling it.': 'أضيفي رقم فودافون كاش قبل تفعيله.', 'Name shown in InstaPay': 'الاسم الظاهر في إنستا باي',
  'Add to Bag': 'أضيفي إلى الحقيبة', 'sold out': 'نفد المخزون', 'in stock': 'متوفر', 'Save': 'حفظ', 'View product': 'عرض المنتج', 'Account menu': 'قائمة الحساب', 'Account': 'الحساب', 'Open shopping bag': 'فتح حقيبة التسوق', 'Shopping bag': 'حقيبة التسوق', 'Open bag': 'فتح الحقيبة', 'Quick navigation': 'تنقل سريع', 'Breadcrumb': 'مسار التنقل', 'Filter by category': 'تصفية حسب الفئة', 'Sort products': 'ترتيب المنتجات', 'Filter by status': 'تصفية حسب الحالة', 'Filter by stock': 'تصفية حسب المخزون', 'Filter by price': 'تصفية حسب السعر', 'Filter by discount': 'تصفية حسب الخصم', 'Filter orders': 'تصفية الطلبات', 'Admin navigation': 'قائمة الإدارة', 'Primary': 'أساسية', 'Mobile': 'قائمة الهاتف', 'Primary': 'أساسية', 'You@example.com': 'you@example.com',
  'The store has no payment method enabled. Contact the store owner.': 'لا توجد وسيلة دفع مفعّلة حاليًا. تواصلي مع صاحب المتجر.', 'Add a scent or two before checking out.': 'أضيفي عطرًا أو اثنين قبل إتمام الشراء.', 'Google sign-in needs a Google OAuth client ID in Vercel before it can be enabled.': 'يتطلب تسجيل الدخول بجوجل إضافة معرّف Google OAuth في Vercel قبل تفعيله.', 'Loading Google sign-in…': 'جارٍ تحميل تسجيل الدخول بجوجل…', 'Google sign-in could not load. Check your connection.': 'تعذر تحميل تسجيل الدخول بجوجل. تحققي من الاتصال بالإنترنت.',
  'Account created. Check your inbox and verify your email, then sign in.': 'تم إنشاء الحساب. تحققي من بريدك الإلكتروني ثم سجّلي الدخول.', 'Password reset link sent. Check your email inbox.': 'تم إرسال رابط إعادة تعيين كلمة المرور. تحققي من بريدك الإلكتروني.', 'Please accept the Terms & Conditions and Privacy Policy.': 'يرجى الموافقة على الشروط والأحكام وسياسة الخصوصية.', 'You have been signed out.': 'تم تسجيل خروجك.', 'Product not found.': 'لم يتم العثور على المنتج.', 'Back to products': 'العودة إلى المنتجات', 'No products match these filters.': 'لا توجد منتجات تطابق عوامل التصفية.', 'Customer preview': 'معاينة العميل', 'Open in store': 'فتح في المتجر', 'This action cannot be undone.': 'لا يمكن التراجع عن هذا الإجراء.', 'It will disappear from the customer store but stay here, and can be restored later.': 'سيختفي من متجر العملاء لكنه سيبقى هنا ويمكن استعادته لاحقًا.', 'Product updated successfully.': 'تم تحديث المنتج بنجاح.', 'Product created successfully.': 'تم إنشاء المنتج بنجاح.', 'Unable to save product. Please check the required fields.': 'تعذر حفظ المنتج. تحققي من الحقول المطلوبة.', 'Unable to save settings.': 'تعذر حفظ الإعدادات.', 'Category updated.': 'تم تحديث الفئة.', 'Category deleted.': 'تم حذف الفئة.', 'Edit category': 'تعديل الفئة', 'Product images': 'صور المنتج', 'Only active products appear in the customer store. Drafts and archived products stay here in the admin.': 'تظهر المنتجات النشطة فقط للعملاء. تبقى المسودات والمنتجات المؤرشفة هنا في لوحة الإدارة.',
  '& up': 'فأعلى', 'Back home': 'العودة إلى الرئيسية',
  'Browse the collection and save the ones that speak to you.': 'تصفحي المجموعة واحفظي العطور التي تعجبكِ.',
  'The moods you’re keeping an eye on.': 'العطور التي ترغبين في العودة إليها.',
  'Nothing saved yet — tap the heart on any scent to keep it here.': 'لم تحفظي أي عطر بعد — اضغطي على القلب لحفظ العطر هنا.',
  'This page wandered off.': 'يبدو أن هذه الصفحة ضلّت الطريق.',
  'Like a good scent trail, it faded. Let’s take you back to the collection.': 'مثل أثر العطر، اختفى الطريق. لنعد بكِ إلى المجموعة.',
  'The three AZ fine fragrance mists standing on bronze satin under golden light': 'معطرات AZ الفاخرة الثلاثة على قماش برونزي تحت ضوء ذهبي',
  'AZ — Bodysplash & Serum': 'AZ — بودي سبلاش وسيروم',
  'AZ Store — Cairo, Egypt': 'AZ Store — القاهرة، مصر',
  'This size is sold out — try another size.': 'هذا الحجم غير متوفر — جرّبي حجمًا آخر.',
  'Black Kiss Intense': 'بلاك كيس إنتنس', 'Warm vanilla, Seductive musk': 'فانيليا دافئة، مسك جذاب',
  'Applied to new products; existing products keep their own threshold.': 'يُطبق على المنتجات الجديدة؛ وتحتفظ المنتجات الحالية بحدودها الخاصة.',
  'For InstaPay and Vodafone Cash, shoppers transfer from their own app and enter the transfer reference. Verify transfers in Orders before marking them paid. These options do not charge or confirm payments automatically.': 'في إنستا باي وفودافون كاش، يحوّل العملاء من تطبيقهم ثم يدخلون الرقم المرجعي للتحويل. تحققي من التحويلات في الطلبات قبل تسجيلها كمدفوعة. هذه الوسائل لا تخصم أو تؤكد المدفوعات تلقائيًا.',
  'units on hand across': 'وحدة متوفرة عبر',
};

function initialLanguage() {
  try { return localStorage.getItem(STORAGE_KEY) === 'ar' ? 'ar' : 'en'; } catch { return 'en'; }
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(initialLanguage);
  const toggleLanguage = useCallback(() => setLanguage((current) => current === 'en' ? 'ar' : 'en'), []);
  const t = useCallback((value) => language === 'ar' ? (translations[value] || value) : value, [language]);

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    try { localStorage.setItem(STORAGE_KEY, language); } catch { /* language still works for this session */ }
  }, [language]);

  useEffect(() => {
    const sync = (event) => { if (event.key === STORAGE_KEY) setLanguage(event.newValue === 'ar' ? 'ar' : 'en'); };
    window.addEventListener('storage', sync);
    return () => window.removeEventListener('storage', sync);
  }, []);

  const value = useMemo(() => ({ language, toggleLanguage, t }), [language, toggleLanguage, t]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const value = useContext(LanguageContext);
  if (!value) throw new Error('useLanguage must be used inside LanguageProvider');
  return value;
}
